version: '3'

services:

    node:
        build:
            context: ./node
            dockerfile: Dockerfile.prod
        image: wsanada/node:prod
        container_name: node
        networks:
            - nodenet

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile.prod
        image: wsanada/nginx:prod
        container_name: nginx
        networks: 
            - nodenet
        ports:
            - "8080:8080"

networks: 
    nodenet:
        driver: bridge